version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: evomysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: evo_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      evonet:
        ipv4_address: 172.16.238.20
  evoserver:
    build: dockerdir
    image: evo/python:1.0
    ports:
      - 5000:80
    container_name: evoserver
    networks:
      evonet:
        ipv4_address: 172.16.238.10

networks:
  evonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
